### ISSUE TITLE
Does Ver 0.1.20 support DND between 2 react-sortable-tree ? If yes, how ?

### ISSUE THREAD

**Issue by LogicMonsters** [fritz-c/react-sortable-tree#118]
Hi I see the approach you have done in the example of [externalNodeExample](https://github.com/fritz-c/react-sortable-tree/tree/master/src/examples/externalNodeExample), and I just tried to implement DND between 2 react sortable trees. But I cannot find a way to pass the "addItem" and "dropCancelled" functions into the second tree. Could you please offer some suggestions ? Thanks in advance !!!

**Comment by stephenc222** [comment]
Since I'm the guy who wrote PR #113  for adding in external nodes, here's my two cents:

The current implementation for the tree component itself doesn't use the props for the _addItem_ and _dropCancelled_ methods of the externally wrapped node, so passing them in won't allow for control of any tree behavior directly, since only the externally wrapped node makes use of them to communicate to the tree. 

What _*may_ work for creating drag and drop between two trees is if you were to wrap the tree's NodeContentRenderer on [L73 ](https://github.com/fritz-c/react-sortable-tree/blob/master/src/node-renderer-default.js#L73) with additionally perhaps the API's external node wrapper. Kind of like how  [this issue #427](https://github.com/react-dnd/react-dnd/issues/427) on the main React-dnd repository recommends how to wrap a component with more than one drag source. This would require passing in a custom NodeContentRenderer prop to the main tree component as well.

However, if this does work, what won't happen automatically is the removal of the first node from the dragged-from tree after dropping in of the node in the second tree, that's something you'd need to anticipate, if that's what you are hoping to occur as well. 

In all likelihood, I don't see this happening cleanly without another PR focused on enabling tree-to-tree communication, as was my experience with adding in the external nodes functionality.

Hope this helps.

_*NOTE: this is purely conjecture and not at all tested or verified._

**Comment by LogicMonsters** [comment]
Thanks for the thorough explanation ! Will you guys consider adding this feature in near future. Since I would say that will absolutly make react-sortable-tree even greater !

**Comment by stephenc222** [comment]
I think that would be an interesting feature to add. Good suggestion.

**Comment by oarashi** [comment]
Does anybody have examples of working code with moving nodes across 2 react sortable trees? (e.g. using NodeContentRenderer as it was mentioned above). 
Thanks!

**Comment by fritz-c** [comment]
Works now as of version 1.0.0. See the storybook linked in the readme for examples.
