### ISSUE TITLE
Custom styles for different level nodes

### ISSUE THREAD

**Issue by dharanidhanapalan** [fritz-c/react-sortable-tree#152]
Hi 
I am using this component in my project and it is pretty good.

I am using only two levels of node in my project and I need different styles for level 1 and level 2. I achieved that by overwriting the CSS.

But when I drag and drop a node from level 2 to level 1, I need to apply level 1 styles for that node. How do I apply that? Is there any solution for that?

**Comment by davo11122** [comment]
Hello.
You can simply extend [Item](https://github.com/fritz-c/react-sortable-tree/blob/master/src/node-renderer-default.js) component through `nodeContentRenderer` property and do whatever you want.

**Comment by dharanidhanapalan** [comment]
@davo11122  Hi
Can you please tell me how to use nodeContentRenderer property? Do you have any sample code by using nodeContentRenderer property ?

**Comment by fritz-c** [comment]
Sorry for the late reply. To change the style according to the depth of the node in the tree, I would recommend using the `path` length in the `generateNodeProps` callback. I have a new example demonstrating that in the Storybook, called "Playing with generateNodeProps": 

https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Playing%20with%20generateNodeProps&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

Note that I would recommend using `className` instead of `style`, for more flexibility.
