### ISSUE TITLE
Avoid nodes from collapsing on input keypress

### ISSUE THREAD

**Issue by arielgk** [fritz-c/react-sortable-tree#198]
I have another component to edit properties from the current selected node,
 Editing child nodes, when some text is entered in an input field in that component. the three collapses.
Example:
https://codesandbox.io/s/k5prlk22mo

any hint to avoid this?

**Comment by fritz-c** [comment]
I moved things around quite a bit to get a working example: https://codesandbox.io/s/o7l32vw3oz

The reason the tree was collapsing every time was because you were regenerating the tree from the flat data every time you edited it. The flat data didn't keep the `expanded` attribute, so it reverted to a collapsed version.

There were a couple more issues related to data handling that you might be able to figure out by looking at the updated version, but if you have any questions please ask.

**Comment by arielgk** [comment]
It make sense. I missed that.
great component and support!
thank you!
