### ISSUE TITLE
conflict w/ bootstrap css?

### ISSUE THREAD

**Issue by sandro-pasquali** [fritz-c/react-sortable-tree#2]
Hi, this is a great component.

When using Bootstrap v3.3.7 the style of the tree seems to break:

![screenshot](https://cloud.githubusercontent.com/assets/657552/18922525/f94fe2ae-8576-11e6-87c6-9872616b7e17.png)

**Comment by fritz-c** [comment]
Thanks for the tip! It looks like this might be a `box-sizing` issue, because I'm using borders to draw those corners. I'll fix it soon.

**Comment by fritz-c** [comment]
Fixed in v0.0.7

**Comment by sandro-pasquali** [comment]
Awesome! Going to publish to npm soon, or more stuff to do?

**Comment by fritz-c** [comment]
It is actually up on npm already, although I haven't really advertised the fact. I want to make sure the api is reasonably hardened before a lot of people start using it. I guess you could call it the result of trauma caused by my react-image-lightbox having to jump major version numbers at a crazy rate because I kept making breaking changes.
