### ISSUE TITLE
Utils Examples Need Improvement

### ISSUE THREAD

**Issue by mcolburn** [fritz-c/react-sortable-tree#208]
The provided examples do not use  react-sortable-tree as an npm package.  Instead, they reference   the src folder:
` import SortableTreeWithoutDndContext as Sortable, {toggleExpandedForAll,} from '../../src/index';`

This does not work when using the npm package:

` import SortableTreeWithoutDndContext as Sortable, {toggleExpandedForAll,} from 'react-sortable-tree';`

I can not figure out how to import the functions exported by tree-data-utils.js.

Please provide examples that import react-sortable-tree rather than src so we can see how it is done.

Thank you!

**Comment by lifejuggler** [comment]
@mcolburn while the source folder do reference the src folder you are not even correctly following the example at all.... instead of this
`    import SortableTreeWithoutDndContext as Sortable, {toggleExpandedForAll,} from '../../src/index';    `

this should be the correct way of using function from tree-data-utils.js

`    import {SortableTreeWithoutDndContext as Sortable, toggleExpandedForAll} from '../../src/index';    `

let me know if this doesn't work for you

**Comment by mcolburn** [comment]
What I am asking for is an example from the perspective of someone who has pulled from npm, not someone who cloned or forked the github repo.  If someone has pulled react-sortable-tree from npm, there is no react-sortable-tree src to refer to.

This does not work:

`import {SortableTreeWithoutDndContext as Sortable, toggleExpandedForAll} from 'react-sortable-tree';
`

The only solution I have found so far is to copy the tree-data-utils.js file into my own development src folder and use it from there.

**Comment by jzoric** [comment]
@mcolburn Hi, I believe [this example](https://codesandbox.io/s/81jvo9zqm2) is what you want. Can you try it?

**Comment by mcolburn** [comment]
Yes, your example worked for me:

`import SortableTree, { toggleExpandedForAll } from "react-sortable-tree";`

Thank you!
