### ISSUE TITLE
Problem with SortableTreeWithoutDndContext

### ISSUE THREAD

**Issue by top1st** [fritz-c/react-sortable-tree#219]
# Reporting a Bug?

Troubleshooting have problem

# Requesting a Feature?

import { SortableTreeWithoutDndContext as SortableTree } from 'react-sortable-tree';

![image](https://user-images.githubusercontent.com/23559697/34171002-d37b67c6-e527-11e7-916e-5c6b60240e90.png)

**Comment by jzoric** [comment]
Hi, 
without a code example it is hard to tell what's wrong. For start, can you create a small example on codesandbox and also look at example [here](https://github.com/fritz-c/react-sortable-tree/blob/master/examples/storybooks/external-node.js).

**Comment by top1st** [comment]
@jzoric  which more example need?
I only imported SortableTreeWithoutDndContext
And i get error

**Comment by jzoric** [comment]
@top1st I asked for code example because I believe you don't have DnD context for the SortableTree. 
In [this](https://codesandbox.io/s/4wj6m99yx7?module=%2FApp.js) codesandbox, if I export the App component without DnD context I will get the same error message as you do, but if I export it with the context everything is working fine.

**Comment by jzoric** [comment]
@top1st Hi, what is the status with this?

**Comment by uptonking** [comment]
I just happened to have the same problem because I simply replaced the import line as described in  `README.md`  Troubleshooting part.

the solution is to look at the [example](https://github.com/fritz-c/react-sortable-tree/blob/master/examples/storybooks/external-node.js), and add another line
`export default DragDropContext(HTML5Backend)(YourComponent);`

**Comment by fritz-c** [comment]
@jzoric Thanks for the helpful followup. I think we can consider this resolved.
