### ISSUE TITLE
onMoveNode doesn't seem to pass treeIndex or path.

### ISSUE THREAD

**Issue by mojo5000** [fritz-c/react-sortable-tree#27]
Capturing an onMoveNode event so I can send an ajax call.  I was expecting { treeData, node, treeIndex, path } but only see treeData and node coming in.  It's therefore difficult to determine the parent and I'd rather not have to do another search for a match by an id.  Let me know if I am missing something!

**Comment by fritz-c** [comment]
I just added this in a release yesterday, so could you make sure first that you have updated to at least `v0.1.7`?

**Comment by mojo5000** [comment]
I retrieved latest, all is good, thanks.  

FYI - side notes, sry if off topic for issue:

1.  When building from source I needed to 'npm install babel-preset-stage-0'.

2.  I'm building in add/edit/delete node functions, modals and buttons.  Any plans on having more of this baked into the component in the future?

3.  I am continually impressed by this component.  As I continue to go deeper into it, you've accounted for a lot of items, and made some nice hooks and utils that are integral.  Thanks for your amazing work.

**Comment by fritz-c** [comment]
1. What syntax was failing to compile? With the current [`.babelrc`](https://github.com/fritz-c/react-sortable-tree/blob/master/.babelrc) I never had issues building on my work and home computers.
1. I do think it would be worthwhile to have documentation explaining how to implement add/delete operations. I don't think it would be good to add baked-in functions, because they'd have to be complex enough to cover all the bases in terms of people's expectations.
For an 'add' example - if I click the <kbd>+</kbd> button on this row, will it append to the children? Will it prepend? Will it add a sibling on the same level? And for delete - will it delete all the children, or shift them up a level?
I will admit that the search functionality of this component breaches this same territory. However, its high degree of coupling with scrolling and node rendering (for highlighting) made it worthwhile to create an opinionated approach to search, such that this common use case could be handled easily by library users. Add/edit/delete have the advantage of only working with the tree data, which can be manipulated without ever having to worry about my library internals.
1. Thanks for the feedback and suggestions! It's really valuable to get a sense of what the library users expect from the component.

I'm going to close this issue as the original problem was resolved, but we can keep up a conversation here about the points mentioned above.
