### ISSUE TITLE
Disabling move node

### ISSUE THREAD

**Issue by clifflo** [fritz-c/react-sortable-tree#37]
Hi I would like to ask if I can if I can disable the moving node functionality for a tree. Also for button how can I add one, as the api does not state clearly how to do so.

**Comment by larsts** [comment]
Hi, 

I'm sure fritz-c can elaborate here, but I know you would need to create your own noderenderer to disable the moving functionality. Check out the nodeContentRenderer option.

As for adding buttons, check out the generateNodeProps option and how this is configured in the included example ([src/examples/basicExample/app.js](https://github.com/fritz-c/react-sortable-tree/blob/master/src/examples/basicExample/app.js))

**Comment by fritz-c** [comment]
Thank you @larsts. 
As larsts said, the [example code](https://github.com/fritz-c/react-sortable-tree/blob/947b00344b647dd4c2fbe00f0d243f94348e9466/src/examples/basicExample/app.js#L292-L303) is a good place to look for the button adding example.

As for disabling moving, I don't have an official way to do it, but the hack explained here might do what you want for now: https://github.com/fritz-c/react-sortable-tree/issues/14#issuecomment-259893522

**Comment by clifflo** [comment]
By the way I have written a typescript definition for your library, so should I make a pull request for you then? Also @fritz-c do you mind let me write the disabling moving for you, perhaps I could clone your repository and then write up a new prop of enable/disable the handle bar.

Also for the length of individual tree node if the text is too long would it wrap? I have tested but I find that it is not able to do so.

**Comment by fritz-c** [comment]
I've not used typescript before, so I'm not exactly sure how it works, but if it will benefit other users of the library I'll merge it in.

As for the move disabling, I would be interested in adding a new prop for it. A `moveDisabled` prop that disables the rendering of the handle (and adds an extra `rowContentsMoveDisabled` class to replace the missing border on the left side of the node).

Text wrapping is not possible right now, at least not in the automatic, browser-handled sense. If you made the `rowHeight` prop tall enough, and added `<br />` or some sort of `pre` style to your text, you could pull it off, but automatic resizing due to height is disabled in favor of using react-virtualized. If you search "react-virtualized" in the issues you can find a few discussions on this matter.

**Comment by clifflo** [comment]
So now for the typescript definition should I make a pull request then?

**Comment by fritz-c** [comment]
Sure, that would be great!

**Comment by clifflo** [comment]
Thanks Chris. So I assume that I would firstly fork your project and then add the relevant typescript definitions to a new folder and then compare to your master branch making a pull request, is that right?

**Comment by fritz-c** [comment]
I'm not sure how typescript definitions work, so I can't comment on the folder part of it, but the rest of that regarding the pull request is correct.

**Comment by rgrohitg** [comment]
Hi,

is the moveDisabled props is added in the latest release?

**Comment by thidasapankaja** [comment]
Is there a way to disable the specific nodes only rather than disabling the drag on entire tree

**Comment by gaeundev** [comment]
> Is there a way to disable the specific nodes only rather than disabling the drag on entire tree

My case was only disabled on the root node, and I used it as below

```
<SortableTree
   {...props}
   canDrag={({treeIndex) => treeIndex>0}
/>
```

![image](https://github.com/frontend-collective/react-sortable-tree/assets/52341210/f9bc73f2-ffc0-4762-bceb-7b30ceea3542)
